# version: "3.11"

# services:

#   flask:
#     build: ./flask
#     container_name: flask
#     restart: always
#     # expose: 
#     ports:
#       - "5000"


#   nginx:
#     build: ./nginx
#     # volumes: 
#     #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#     container_name: nginx
#     depends_on:
#       - flask
#     restart: always
#     ports:
#       - "80:80"



# version: '3.8'

# services:
#   flask:
#     build: ./flask
#     ports:
#       - "5000:5000"  # Expose Flask app port

#   nginx:
#     image: nginx:latest
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount your Nginx configuration
#     ports:
#       - "80:80"    # Expose Nginx port

# volumes:
#   nginx-conf:  # Optional volume to persist Nginx configuration changes



version: '3.11'

services:
    flask:
      build: ./flask
      container_name: flask
      restart: always
      expose:
        - "5000:5000"


    nginx:
      build: ./nginx
      container_name: nginx
      restart: always
      ports:
        - "80:80"