version: "3.11"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    # expose: 
    ports:
      - "5000"


  nginx:
    build: ./nginx
    # volumes: 
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: nginx
    depends_on:
      - flask
    restart: always
    ports:
      - "80:80"
